# Generated by Django 4.2.23 on 2025-08-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_admin",),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("agent", "Agent"),
                    ("customer", "Customer"),
                    ("doctor", "Doctor"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
